package dependencies

object Versions {
    const val ACTIVITY_KTX = "1.0.0"
    const val ANDROID_PLUGIN = "3.6.0"
    const val APP_COMPAT = "1.1.0"
    const val CHUCKER = "3.0.1"
    const val CONSTRAINT_LAYOUT = "2.0.0-beta4"
    const val RECYCLER_VIEW = "1.1.0"
    const val COROUTINES = "1.3.2-1.3.60"
    const val DAGGER = "2.26"
    const val DAGGER_ASSISTED = "0.5.2"
    const val FOQA = "0.1.13"
    const val FRAGMENT = "1.2.0-rc02"
    const val KOTLIN = "1.3.61"
    const val KTX_CORE = "1.2.0-rc01"
    const val LAMAH = "1.0.11"
    const val LEAK_CANARY = "2.2-SNAPSHOT"
    const val LIFECYCLE = "2.2.0-rc03"
    const val LOCALIZATION_PLUGIN = "1.0.19"
    const val MAPBOX_NAVIGATION = "0.42.4"
    const val MAPBOX_SDK = "8.6.1"
    const val MATERIAL = "1.2.0-alpha03"
    const val MOCKITO = "3.2.4"
    const val MOCKITO_KOTLIN = "2.2.0"
    const val MOSHI = "1.9.2"
    const val OK_HTTP = "4.2.2"
    const val FIREBASE_MESSAGING = "20.1.0"
    const val ROOM = "2.2.3"
    const val RETROFIT = "2.7.0"
    const val SIMPLE_STACK = "2.1.2"
    const val THREE_TEN_ABP = "1.2.1"
    const val TIMBER = "4.7.1"
    const val VERSIONS_PLUGIN = "0.27.0"
    const val GOOGLE_SERVICES_PLUGIN = "4.3.2"
    const val RATING_BAR_VIEW = "1.5.0"

    const val ANDROIDX_TEST = "1.2.0"
    const val KOTLIN_TEST_ASSERTIONS = "3.4.2"
    const val JUNIT = "4.13-rc-1"
    const val JUNIT_KTX = "1.1.1"
    const val ESPRESSO = "3.2.0"
}
